---
version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"

phases:
  install:
    commands:
    - echo "Setup VirtualEnv"
    - python3 -m venv .venv
    - . .venv/bin/activate
    - echo "Install requirements"
    - pip3 install -r requirements.txt

  build:
    commands:
    - echo "Run unit tests"
    - python3 manage.py test

  post_build:
    commands:
    - rm -rf db.sqlite3 .git .venv # the quickest way to exclude from the zipped artifact

artifacts:
  files:
  - "**/*"
  name:
    prod-provisioning-app-$(date +%y%m%d-%H%M%S)

