---
version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"

phases:
  install:
    commands:
      - echo "Install system packages"
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update && apt-get install -y zip
      - echo "Setup VirtualEnv"
      - python3 -m venv .venv
      - . .venv/bin/activate
      - echo "Install requirements"
      - pip3 install -r requirements.txt

  build:
    commands:
      - echo "Run unit tests"
      - python3 manage.py test

  post_build:
    commands:
      # note: all the stages are executed, no matter whether the previous stage was failed (except the install)
      #       so to skip the stage we have to check conditions (env vars)
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo "Create an app archive (including .venv dir)"; zip -r app.zip . -x db.sqlite3 \*.git\*; fi

artifacts:
  files:
    - app.zip
  name:
    prod-provisioning-app-$(date +%y%m%d-%H%M%S)
