---
version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"

phases:
  install:
    commands:
      - echo "Setup VirtualEnv"
      - python3 -m venv .venv
      - source .venv/bin/activate
      - echo "Install requirements"
#      - pip3 install -r requirements.txt

  build:
    commands:
      - echo "Run unit tests"
#      - python3 manage.py test

  post_build:
    commands:
      - echo "Create an app archive"
      - ls -la .