# django-q worker
FROM python:3.6

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends mysql-client python3-dev python3-setuptools python3-pip libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev tcl8.6-dev tk8.6-dev python-tk && apt-get clean

RUN mkdir /www
WORKDIR /www

ADD ./requirements.txt /www/requirements.txt
RUN pip install -r requirements.txt
ADD . /www

RUN python manage.py migrate --noinput

EXPOSE 8000
CMD ["python", "manage.py", "qcluster"]
